apiVersion: v1
kind: Service
metadata:
  labels:
    app: klausur-todo-svc
  name: klausur-todo-svc
  namespace: philipp-erath
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-80
    nodePort: 32542
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: klausur-todo
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}